services:
  db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      start_period: 1m
    logging:
      driver: json-file
      options:
        max-size: 1M
        max-file: 10

  dnsviz:
    image: ghcr.io/dodancs/dnsvizwww:local
    restart: always
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SECRET_KEY
      - ALLOWED_HOSTS
      - DEBUG
      - TZ
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - 80:8000
    networks:
      - default
    logging:
      driver: json-file
      options:
        max-size: 1M
        max-file: 10

networks:
  default:

